# generated by datamodel-codegen:
#   filename:  pxcodes.yaml
#   timestamp: 2023-09-11T09:12:05+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class Admin(BaseModel):
    is_final: Optional[bool] = Field(None, alias='isFinal', example=True)
    tags: Optional[List[str]] = None
    todo_creation: Optional[str] = Field(None, alias='todoCreation')


class Note(BaseModel):
    text: Dict[str, str]
    is_mandatory: bool = Field(..., alias='isMandatory')


class Code(BaseModel):
    code: Optional[str] = Field(None, example='123234a')
    unordered_children: Optional[List[str]] = Field(None, alias='unorderedChildren')
    """
    Any children in random order. The children MUST exist in /codes/code
    """
    label: Optional[Dict[str, str]] = None
    rank: Optional[Dict[str, str]] = None
    notes: Optional[List[Note]] = None


class Grouping(BaseModel):
    label: Optional[Dict[str, str]] = None
    rank: Optional[Dict[str, str]] = None
    codes: Optional[List[Code]] = None


class PxCodes(BaseModel):
    id: str = Field(..., example='123234a')
    admin: Optional[Admin] = None
    label: Optional[Dict[str, str]] = None
    codes: List[Code]
    elimination_possible: Optional[bool] = Field(
        None, alias='eliminationPossible', example=True
    )
    """
    May this variable be eliminnated. If True and eliminationCode is empty use Sum.
    """
    elimination_code: Optional[str] = Field(
        None, alias='eliminationCode', example='tot'
    )
    """
    Value is the code to use for eliminnating the variable
    """
    groupings: Optional[List[Grouping]] = None
