# generated by datamodel-codegen:
#   filename:  pxstatistics.yaml
#   timestamp: 2023-09-11T09:16:54+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class Contact(BaseModel):
    phone: Optional[str] = None
    email: Optional[str] = Field(None, example='epost@epost.no')
    """
    Personal or functional
    """
    name: Optional[Dict[str, str]] = None
    raw: Optional[Dict[str, str]] = None


class PxStatistics(BaseModel):
    id: str = Field(..., example=8765)
    """
    Id of a group of tables in the registry of statistics.
    """
    update_frequency: Optional[Dict[str, str]] = Field(None, alias='updateFrequency')
    meta_id: Optional[str] = Field(None, alias='metaId', example='KORTNAVN:kpi')
    """
    Will be added to metaid on table level. lead to https://www.ssb.no/en/priser-og-prisindekser/konsumpriser/statistikk/konsumprisindeksen#om-statistikken
    """
    subject_code: Optional[str] = Field(None, alias='subjectCode', example='be')
    subject_text: Optional[Dict[str, str]] = Field(None, alias='subjectText')
    upcoming_releases: Optional[List[str]] = Field(None, alias='upcomingReleases')
    contacts: Optional[List[Contact]] = None
