openapi: 3.0.3
info:
  title: Klass uttrekk for PXCodes
  description: |-
    This is a sample PxCodes Store Server based on the OpenAPI 3.0 specification.  
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: PxCodes
    description: Everything about your PxCodess
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /PxCodes/{id}:
    get:
      tags:
        - PxCodes
      summary: Find PxCodes by ID
      description: Returns a single PxCodes
      operationId: getPxCodesById
      parameters:
        - name: id
          in: path
          description: ID of PxCodes to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PxCodes'          
            application/xml:
              schema:
                $ref: '#/components/schemas/PxCodes'
        '400':
          description: Invalid ID supplied
        '404':
          description: PxCodes not found
components:
  schemas:
    PxCodes:
      description: For one variable, this should hold all the information needed to create vs and agg files and the VALUES and CODES px-keywords, and partially for elimination. 
      required:
        - id
        - labels
        - sortValueitemsOn
        - valueitems
        - eliminationPossible
      type: object
      properties:
        id:
          type: string
          example: 123234a
        admin:
          type: object
          properties:
            isFinal:
              type: boolean
              example: true
            tags:
              type: array
              items:
                 type: string
            todoCreation:
              type: string
        sortValueitemsOn:
          $ref: '#/components/schemas/SortValueitemsOn'
        label:
          $ref: '#/components/schemas/StringByLanguage'
        valueitems:
           type: array
           items:
               $ref: '#/components/schemas/Valueitem'
        eliminationPossible:
                    type: boolean
                    example: True
                    description: May this variable be eliminnated. If True and eliminationCode is empty use Sum.
        eliminationCode:
                    type: string
                    example: tot
                    description: Value is the code to use for eliminnating the variable
        sortGroupingsOn:
           type: string
           enum:
              - filenameBase
              - label
              - rank
           description: Sets the order of the groupings in the dropdown  
        groupings:
          type: array
          description: List where an element is a grouping. A grouping is a list of mothers. The code of a mother must not be present in the root-valueitems.
            The children of a mother must be present in the root-valueitems and must be a unique list.
            The child may have many mothers.
          required:
            - filenameBase
            - label
            - sortValueitemsOn
            - valueitems
          items:
             type: object
             properties:
                filenameBase:
                  type: string
                label:
                   $ref: '#/components/schemas/StringByLanguage'
                rank:
                   $ref: '#/components/schemas/StringByLanguage'
                sortValueitemsOn:
                   $ref: '#/components/schemas/SortValueitemsOn'
                   description: How to sort the list of mothers. The children will be sorted by the root-sortValueitemsOn  
                valueitems:
                  type: array
                  items:
                     $ref: '#/components/schemas/Valueitem'
                  description: The mothers
    Valueitem:
      type: object
      properties:
          code:
            type: string
            example: 123234a
          unorderedChildren:
            description: "Any children in random order. The children MUST exist in 
               root-valueitems"
            type: array
            items:
              type: string
          label:
            $ref: '#/components/schemas/StringByLanguage'
          rank:
            $ref: '#/components/schemas/StringByLanguage'
          notes:
            $ref: '#/components/schemas/Notes'          
            
    Notes:
      type: array
      items:
        $ref: '#/components/schemas/Note'
    Note:
      type: object
      required:
        - text
        - isMandatory
      properties:
        text: 
           $ref: '#/components/schemas/StringByLanguage'
        isMandatory:
          type: boolean
            
    SortValueitemsOn:  
            type: string
            enum:
              - code
              - label
              - rank        
          
    StringByLanguage:
      type: object
      additionalProperties:
        type: string   
                





