openapi: 3.0.3
info:
  title: PxMetadata
  description: |-
    This is an abuse of OpenAPI 3.0 just to make a json schema specification for PxMetadata.
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: PxMetadata
    description: Everything about your PxMetadata
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /PxMetadata/{id}:
    get:
      tags:
        - PxMetadata
      summary: Find PxMetadata by ID
      description: Returns a single PxMetadata
      operationId: getPxMetadataById
      parameters:
        - name: id
          in: path
          description: ID of PxMetadata to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PxMetadata'
            application/xml:
              schema:
                $ref: '#/components/schemas/PxMetadata'
        '400':
          description: Invalid ID supplied
        '404':
          description: PxMetadata not found
components:
  schemas:
    PxMetadata:
      required:
        - dataset
      type: object
      description: Outer class
      properties:
        dataset:
          description: Payload
          type: object
          required:
            - tableId
            - baseTitle
            - timeDimension
            - measurements
          properties:
            tableId:
              type: string
              description: "example: '07459' To be used as id in PxWeb Url"
            storedDecimals:
              type: integer
              description: "How many decimals should be stored in the PxFile. Default is the max number of decimals shown."
            statisticsId:
              type: string
              description: "Id of group of tables in the registry of statistics. example: '8765'"
            dataFile:
              type: string
              description: "TODO: Er dette en filsti eller en url. required? Adress to the parquet-file with datadata"
            outputFileName:
              type: string
              description: "Name of the output file. For multilingual defaults to tab_{tableId} or tab_{tableId}_{language} if not multilingual"
            matrix:
              type: string
              description: "The matrix of the table. Defaults to outputFileName excluding language suffix"
            baseTitle:
              type: object
              additionalProperties:
                type: string
              description: "Text to which tableid is prefixed and _by_ variable list is appended. Is used for the CONTENTS keyword. example: no Utenrikshandel med varer"
            searchKeywords:
              type: object
              additionalProperties:
                type: array
                items:
                  type: string
              description: "Array of keywords by language for search. Is used for the SYNONYMS keyword. example:'{en: [External trade, export]}'"
            notes:
              $ref: '#/components/schemas/Notes'
            cellNotes:
              type: array
              items:
                $ref: '#/components/schemas/CellNote'
            timeDimension:
              type: object
              properties:
                columnName:
                  type: string
                  description: name of column in dataset
                code:
                  type: string
                  description: the code of the dimension( aka variable). Defaults to columName if missing
                timePeriodFormat:
                  type: string
                  description: "example: yyyy"
                isHeading:
                  type: boolean
                  description: If true the dimension is a heading otherwise it is a stub
                label:
                  $ref: '#/components/schemas/StringByLanguage'
                metaId:
                  type: array
                  description: For MetaId keyword
                  items:
                    type: string
            codedDimensions:
              type: array
              description: Also known as classification variables
              items:
                 $ref: '#/components/schemas/CodedDimension'
            measurements:
              type: array
              description: Also known as content variables
              items:
                $ref: '#/components/schemas/Measurement'
            metaId:
              type: array
              description: For MetaId keyword
              items:
                type: string
            rowMissing:
               type: string
               description: Value to insert in data when row is missing.
               default: "."
            cellMissing:
               type: string
               description: Value to insert in data when cell is missing.
               default: "."
            officialStatistics:
               type: boolean
               default: false
            copyright:
               type: boolean
               default: false
            firstPublished:
               type: string
               description: The date when the data cube was first published in the format CCYYMMDD hh:mm
            attributes:
              type: array
              items:
                type: object
                properties:
                  columnName:
                    type: string
                    description: name of column in dataset
                  code:
                    type: string
                    description: the code of the measurement
                  codelistId:
                    type: string
                    description: A Link to a PxCodes document


    CodedDimension:
                type: object
                required:
                  - columnName
                  - codelistId
                properties:
                  columnName:
                    type: string
                    description: name of column in dataset
                  code:
                    type: string
                    description: the code of the dimension( aka variable). Defaults to columName if missing
                  isGeoVariableType:
                    type: boolean
                    default: false
                    description: Geo variable or not
                  variableType:
                    type: string
                    description: Variable type
                    default: N
                  isHeading:
                    type: boolean
                    description: If true the dimension is a heading otherwise it is a stub
                  codelistId:
                    type: string
                    description: A Link to a PxCodes document
                  labelConstructionOption:
                    type: string
                    enum:
                      - code
                      - text
                      - code_text
                      - text_code
                    description: Construct label for codelist entry as text or code or text then code or code then text
                  label:
                    $ref: '#/components/schemas/StringByLanguage'
                  doublecolumn:
                     type: boolean
                     default: false
                     description: Applies only to some of the file-export formats. See DOUBLECOLUMN-keyword
                  notes:
                    $ref: '#/components/schemas/Notes'
                  metaId:
                    type: array
                    description: For MetaId keyword
                    items:
                      type: string

    Measurement:
            type: object
            required:
              - columnName
              - label
              - showDecimals
              - aggregationAllowed
              - unitOfMeasure
            properties:
              columnName:
                type: string
                description: name of column in dataset
              code:
                type: string
                description: the code of the measurement. Defaults to columName if missing
              label:
                $ref: '#/components/schemas/StringByLanguage'
              showDecimals:
                type: integer
                description: number of decimal to use in output
              priceType:
                type: string
                enum:
                  - Current
                  - Fixed
                description: Empty if not a price
              isSeasonallyAdjusted:
                type: boolean
              isWorkingdaysAdjusted:
                type: boolean
              aggregationAllowed:
                type: boolean
                description: Is it meaningfull to sum this measurement
              basePeriod:
                type: object
                additionalProperties:
                  type: string
                description: "For index example: '1. kvartal 2010'"
              referencePeriod:
                type: object
                additionalProperties:
                  type: string
                description: Text with information on the reference period for the statistics.
              rank:
                type: object
                additionalProperties:
                  type: string
                description: Sort order for measurement in dimension, document order is default
              unitOfMeasure:
                type: object
                additionalProperties:
                  type: string
                description: Text including unit multiplier
              notes:
                $ref: '#/components/schemas/Notes'
              metaId:
                type: array
                description: For MetaId keyword
                items:
                  type: string

    CellNote:
      type: object
      required:
        - attachment
        - text
        - isMandatory
      description: "Note on a cell/subcube"
      properties:
        attachment:
          type: array
          description: "Attaches the text on a point/subcube of the cube. The array has one or zero entries for each dimension. No entry for a dimension means everything."
          items:
            type: object
            required:
              - dimensionCode
              - valueCode
            properties:
               dimensionCode:
                  type: string
                  description: "The code of the dimension (found in config for time and measure)"
               valueCode:
                  type: string
                  description: "The code of the Value"
        text:
           $ref: '#/components/schemas/StringByLanguage'
        isMandatory:
          type: boolean

    Notes:
      type: array
      items:
        $ref: '#/components/schemas/Note'
    Note:
      type: object
      required:
        - text
        - isMandatory
      properties:
        text:
           $ref: '#/components/schemas/StringByLanguage'
        isMandatory:
          type: boolean

    StringByLanguage:
      type: object
      additionalProperties:
        type: string
