openapi: 3.0.3
info:
  title: PxStatistics
  description: |-
    This is a sample PxStatistics Store Server based on the OpenAPI 3.0 specification.  
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: PxStatistics
    description: Gets data from your registry of statistics. <br>
       The underlying model is that tables are put on the web in groups. All tables in the group
       are published at the same time and with the same frequensy. They also share subject in the "menutree" and may share contact info. They have the same Information about the statistics page.
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /PxStatistics/{id}:
    get:
      tags:
        - PxStatistics
      summary: Find PxStatistics by ID
      description: Returns a single PxStatistics
      operationId: getPxStatisticsById
      parameters:
        - name: id
          in: path
          description: ID of PxStatistics to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PxStatistics'          
            application/xml:
              schema:
                $ref: '#/components/schemas/PxStatistics'
        '400':
          description: Invalid ID supplied
        '404':
          description: PxStatistics not found
components:
  schemas:
    PxStatistics:
      description: Holds information of a publishing system nature, or registry of statistics if you like. The asumption behind subjectCode and subjectText is that your tables may be put in a menu tree. Subject is the first level in that tree. 
      required:
        - id
        - subjectCode
        - subjectText
        - contacts
      type: object
      properties:
            id:
              type: string
              description: "Id of a group of tables in the registry of statistics. example: 8765"
            updateFrequency:
              type: object
              additionalProperties:
                type: string
              description: "Must mean the same in all languages. example: Quarterly"
            metaId:
                type: array
                description: "Will be added to metaid on table level. 'KORTNAVN:kpi' lead to https://www.ssb.no/en/priser-og-prisindekser/konsumpriser/statistikk/konsumprisindeksen#om-statistikken "
                externalDocs:
                   description: This does not appear in pydantic 
                   url: https://swagger.io
                items:
                  type: string
            subjectCode:
              type: string
              description: "example: be"
            subjectText:
              type: object
              minProperties: 1
              additionalProperties:
                type: string
              description: "example en:Population"
            upcomingReleases:
              type: array
              items:
                type: string
              description: "example: 2024-02-05 08:00:00.0 TODO sjekk at dato i riktig format"
            contacts:
              type: array
              items:     
                  type: object
                  properties:
                    phone:
                      type: string               
                    email:                   
                      type: string
                      description: Personal or functional
                    name:
                      type: object
                      description: Name of contact in all languages. Personal or functional
                      additionalProperties:                    
                        type: string
                    raw:
                      type: object
                      additionalProperties:
                          type: string
                      description: If this has value it replaces the 3 other fields, so they are ignored. Anything, will be put under contact as is. 
            